
// This file has been generated by the GUI designer. Do not modify.
namespace DBEjemplo
{
	public partial class wAlumnos
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry txtNombre;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry txtAP;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry txtAM;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.ComboBox cmbCarrera;
		
		private global::Gtk.Button btnGuardar;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView vwAlumnos;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DBEjemplo.wAlumnos
			this.Name = "DBEjemplo.wAlumnos";
			this.Title = global::Mono.Unix.Catalog.GetString ("wAlumnos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DBEjemplo.wAlumnos.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Agregar alumno");
			this.vbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre: ");
			this.hbox11.Add (this.label9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label9]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry ();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '•';
			this.hbox11.Add (this.txtNombre);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.txtNombre]));
			w3.Position = 1;
			this.vbox3.Add (this.hbox11);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox11]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Paterno: ");
			this.hbox12.Add (this.label10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label10]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.txtAP = new global::Gtk.Entry ();
			this.txtAP.CanFocus = true;
			this.txtAP.Name = "txtAP";
			this.txtAP.IsEditable = true;
			this.txtAP.InvisibleChar = '•';
			this.hbox12.Add (this.txtAP);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.txtAP]));
			w6.Position = 1;
			this.vbox3.Add (this.hbox12);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox12]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido Materno: ");
			this.hbox9.Add (this.label7);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label7]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.txtAM = new global::Gtk.Entry ();
			this.txtAM.CanFocus = true;
			this.txtAM.Name = "txtAM";
			this.txtAM.IsEditable = true;
			this.txtAM.InvisibleChar = '•';
			this.hbox9.Add (this.txtAM);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.txtAM]));
			w9.Position = 1;
			this.vbox3.Add (this.hbox9);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Carrera: ");
			this.hbox10.Add (this.label8);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label8]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.cmbCarrera = global::Gtk.ComboBox.NewText ();
			this.cmbCarrera.Name = "cmbCarrera";
			this.hbox10.Add (this.cmbCarrera);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.cmbCarrera]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox3.Add (this.hbox10);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox10]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.btnGuardar = new global::Gtk.Button ();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.vbox3.Add (this.btnGuardar);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.btnGuardar]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Lista de alumnos");
			this.vbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label5]));
			w15.Position = 6;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.vwAlumnos = new global::Gtk.TreeView ();
			this.vwAlumnos.CanFocus = true;
			this.vwAlumnos.Name = "vwAlumnos";
			this.GtkScrolledWindow.Add (this.vwAlumnos);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w17.Position = 7;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 301;
			this.Show ();
			this.btnGuardar.Clicked += new global::System.EventHandler (this.OnBtnGuardarClicked);
		}
	}
}
