
// This file has been generated by the GUI designer. Do not modify.
namespace DBEjemplo
{
	public partial class wPrestamos
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DBEjemplo.wPrestamos
			this.Name = "DBEjemplo.wPrestamos";
			this.Title = global::Mono.Unix.Catalog.GetString ("wPrestamos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
