
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnAlumnos;
	
	private global::Gtk.Button btnArticulos;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button btnPrestamos;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView vwConsultas;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnAlumnos = new global::Gtk.Button ();
		this.btnAlumnos.CanFocus = true;
		this.btnAlumnos.Name = "btnAlumnos";
		this.btnAlumnos.UseUnderline = true;
		this.btnAlumnos.Label = global::Mono.Unix.Catalog.GetString ("Alumnos");
		this.hbox1.Add (this.btnAlumnos);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAlumnos]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnArticulos = new global::Gtk.Button ();
		this.btnArticulos.CanFocus = true;
		this.btnArticulos.Name = "btnArticulos";
		this.btnArticulos.UseUnderline = true;
		this.btnArticulos.Label = global::Mono.Unix.Catalog.GetString ("Artículos");
		this.hbox1.Add (this.btnArticulos);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnArticulos]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnPrestamos = new global::Gtk.Button ();
		this.btnPrestamos.CanFocus = true;
		this.btnPrestamos.Name = "btnPrestamos";
		this.btnPrestamos.UseUnderline = true;
		this.btnPrestamos.Label = global::Mono.Unix.Catalog.GetString ("Prestamos");
		this.hbox2.Add (this.btnPrestamos);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnPrestamos]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.vwConsultas = new global::Gtk.TreeView ();
		this.vwConsultas.CanFocus = true;
		this.vwConsultas.Name = "vwConsultas";
		this.GtkScrolledWindow.Add (this.vwConsultas);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w7.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnAlumnos.Clicked += new global::System.EventHandler (this.OnBtnAlumnosClicked);
		this.btnArticulos.Clicked += new global::System.EventHandler (this.OnBtnArticulosClicked);
		this.btnPrestamos.Clicked += new global::System.EventHandler (this.OnBtnPrestamosClicked);
	}
}
